# Generated by Django 4.2 on 2023-07-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="garageitem",
            old_name="cost_in_credits",
            new_name="duration",
        ),
        migrations.RemoveField(
            model_name="garageitem",
            name="item_type",
        ),
        migrations.RemoveField(
            model_name="garageitem",
            name="primary_material",
        ),
        migrations.AddField(
            model_name="garageitem",
            name="add_generic_loc",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="garageitem",
            name="auto_relist",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="garageitem",
            name="bid_starts",
            field=models.DecimalField(
                blank=True, decimal_places=3, default=0.0, max_digits=30, null=True
            ),
        ),
        migrations.AddField(
            model_name="garageitem",
            name="with_anything",
            field=models.BooleanField(default=False),
        ),
    ]
