# Generated by Django 4.2 on 2023-07-29 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0003_remove_garageitem_category_garageitemcategory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="garageitem",
            old_name="lat",
            new_name="meet_up_lat",
        ),
        migrations.RenameField(
            model_name="garageitem",
            old_name="lng",
            new_name="meet_up_lng",
        ),
        migrations.RenameField(
            model_name="garageitem",
            old_name="location_name",
            new_name="meet_up_loc",
        ),
    ]
