# Generated by Django 4.2 on 2023-07-30 14:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("garage", "0004_rename_lat_garageitem_meet_up_lat_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="garageitem",
            name="item_owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="garage_item_user",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
