# Generated by Django 4.2 on 2023-07-30 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("garage", "0005_garageitem_item_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="garageitem",
            name="ends_in",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
