# Generated by Django 4.2 on 2025-09-23 14:59

from django.db import migrations, models
import user_profile.models
import user_profile.validators


class Migration(migrations.Migration):

    dependencies = [
        ("user_profile", "0002_personalinfo_is_online"),
    ]

    operations = [
        migrations.AlterField(
            model_name="admininfo",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=user_profile.models.get_default_profile_image,
                null=True,
                upload_to=user_profile.models.avatar_upload_to,
                validators=[user_profile.validators.validate_avatar_file],
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="id_card_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=user_profile.models.id_document_upload_to,
                validators=[user_profile.validators.validate_id_document],
            ),
        ),
        migrations.AlterField(
            model_name="personalinfo",
            name="photo",
            field=models.ImageField(
                blank=True,
                default=user_profile.models.get_default_profile_image,
                null=True,
                upload_to=user_profile.models.avatar_upload_to,
                validators=[user_profile.validators.validate_avatar_file],
            ),
        ),
    ]
