# Generated by Django 4.2 on 2025-09-23 16:38

from django.db import migrations, models
import journeys.models


class Migration(migrations.Migration):

    dependencies = [
        ("journeys", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="journeystepmedia",
            name="file",
            field=models.FileField(
                blank=True,
                max_length=500,
                upload_to=journeys.models.journey_step_media_upload_to,
            ),
        ),
    ]
