# Generated by Django 4.2 on 2023-07-16 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import trade_up_league.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tags", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=1000, null=True)),
                ("caption", models.TextField(blank=True, null=True)),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=trade_up_league.models.upload_episode_path,
                    ),
                ),
                (
                    "date_published",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="date published"
                    ),
                ),
                ("views", models.IntegerField(blank=True, default=0, null=True)),
                ("trending_no", models.IntegerField(blank=True, default=0, null=True)),
                ("active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "likes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="episode_likes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "shared_episodes",
                    models.ManyToManyField(
                        blank=True,
                        related_name="shared_episode_users",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="episode_tags", to="tags.tag"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
