name: Backend CI

on:
  push:
    paths:
      - 'swapwing_backend/**'
      - '.github/workflows/backend-tests.yml'
  pull_request:
    paths:
      - 'swapwing_backend/**'
      - '.github/workflows/backend-tests.yml'

jobs:
  tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: swapwing_backend
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y libpq-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest with coverage
        env:
          DJANGO_SECRET_KEY: test-secret
        run: pytest
